# Generated by Django 5.2.12 on 2026-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=160)),
                ('subheadline', models.CharField(blank=True, max_length=180)),
                ('hero_intro', models.TextField()),
                ('professional_summary', models.TextField()),
                ('development_journey', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('years_of_experience', models.PositiveIntegerField(default=3)),
                ('availability_text', models.CharField(default='Available for freelance and full-time roles', max_length=120)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('hero_badge', models.CharField(blank=True, max_length=120)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('profile_image_url', models.URLField(blank=True)),
                ('profile_image_alt', models.CharField(blank=True, max_length=160)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_primary', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('file_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_primary', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Developer Portfolio', max_length=120)),
                ('site_title', models.CharField(default='Premium Full Stack Developer Portfolio', max_length=180)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('footer_tagline', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_location', models.CharField(blank=True, max_length=120)),
                ('hire_me_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('booking_url', models.URLField(blank=True)),
                ('office_hours', models.CharField(blank=True, max_length=120)),
                ('support_dark_mode', models.BooleanField(default=True)),
                ('contact_cta_title', models.CharField(default='Let us build something worthwhile', max_length=140)),
                ('contact_cta_text', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('og_image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
