import type { DashboardCollections, DashboardFieldOption, DashboardResourceConfig } from '../types/dashboard'

function optionFromCollection(
  collections: DashboardCollections,
  collectionKey: string,
  labelKey: string,
): DashboardFieldOption[] {
  return (collections[collectionKey] || []).map((item) => ({
    label: String(item[labelKey] ?? `Item ${String(item.id ?? '')}`),
    value: Number(item.id),
  }))
}

const projectCategoryOptions: DashboardFieldOption[] = [
  { label: 'Web Apps', value: 'web-apps' },
  { label: 'School Systems', value: 'school-systems' },
  { label: 'Pharmacy Systems', value: 'pharmacy-systems' },
  { label: 'Blog Platforms', value: 'blog-platforms' },
  { label: 'AI Tools', value: 'ai-tools' },
  { label: 'Portfolio / Business Systems', value: 'portfolio-business-systems' },
]

const projectStatusOptions: DashboardFieldOption[] = [
  { label: 'Completed', value: 'completed' },
  { label: 'Ongoing', value: 'ongoing' },
  { label: 'MVP', value: 'mvp' },
]

export const DASHBOARD_RESOURCES: DashboardResourceConfig[] = [
  {
    key: 'profiles',
    label: 'Profile',
    singular: 'Profile',
    endpoint: '/dashboard/profiles/',
    titleKey: 'full_name',
    descriptionKey: 'headline',
    fields: [
      { name: 'full_name', label: 'Full Name', type: 'text' },
      { name: 'headline', label: 'Headline', type: 'text' },
      { name: 'subheadline', label: 'Subheadline', type: 'text' },
      { name: 'hero_intro', label: 'Hero Intro', type: 'textarea', rows: 4 },
      { name: 'professional_summary', label: 'Professional Summary', type: 'textarea', rows: 5 },
      { name: 'development_journey', label: 'Development Journey', type: 'textarea', rows: 5 },
      { name: 'mission', label: 'Mission', type: 'textarea', rows: 4 },
      { name: 'strengths', label: 'Strengths', type: 'list', helperText: 'One item per line.' },
      { name: 'highlights', label: 'Highlights JSON', type: 'json', helperText: 'Use an array like [{"label":"CGPA","value":"3.54"}].', defaultValue: '[]' },
      { name: 'years_of_experience', label: 'Years of Experience', type: 'number' },
      { name: 'availability_text', label: 'Availability Text', type: 'text' },
      { name: 'primary_email', label: 'Primary Email', type: 'email' },
      { name: 'secondary_email', label: 'Secondary Email', type: 'email' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'whatsapp_number', label: 'WhatsApp Number', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'linkedin_url', label: 'LinkedIn URL', type: 'url' },
      { name: 'github_url', label: 'GitHub URL', type: 'url' },
      { name: 'website_url', label: 'Website URL', type: 'url' },
      { name: 'hero_badge', label: 'Hero Badge', type: 'text' },
      { name: 'profile_image', label: 'Profile Image Upload', type: 'file', accept: 'image/*', previewKey: 'profile_image_source' },
      { name: 'profile_image_url', label: 'Profile Image URL', type: 'url' },
      { name: 'profile_image_alt', label: 'Profile Image Alt', type: 'text' },
      { name: 'is_primary', label: 'Primary Profile', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    key: 'contentSections',
    label: 'Section Copy',
    singular: 'Section Copy',
    endpoint: '/dashboard/content-sections/',
    titleKey: 'label',
    descriptionKey: 'key',
    fields: [
      { name: 'key', label: 'Key', type: 'text', helperText: 'Examples: hero, about, skills, services, projects, experience, certificates, testimonials, gallery, contact.' },
      { name: 'label', label: 'Label', type: 'text' },
      { name: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 4 },
      { name: 'extra_text', label: 'Extra Text', type: 'textarea', rows: 4 },
      { name: 'items', label: 'Items', type: 'list', helperText: 'One line per chip, role, or option.' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'siteSettings',
    label: 'Site Settings',
    singular: 'Site Setting',
    endpoint: '/dashboard/site-settings/',
    titleKey: 'site_name',
    descriptionKey: 'site_title',
    fields: [
      { name: 'site_name', label: 'Site Name', type: 'text' },
      { name: 'site_title', label: 'Site Title', type: 'text' },
      { name: 'meta_description', label: 'Meta Description', type: 'textarea', rows: 4 },
      { name: 'meta_keywords', label: 'Meta Keywords', type: 'text' },
      { name: 'footer_tagline', label: 'Footer Tagline', type: 'text' },
      { name: 'contact_email', label: 'Contact Email', type: 'email' },
      { name: 'contact_phone', label: 'Contact Phone', type: 'text' },
      { name: 'contact_location', label: 'Contact Location', type: 'text' },
      { name: 'hire_me_email', label: 'Hire Me Email', type: 'email' },
      { name: 'whatsapp_url', label: 'WhatsApp URL', type: 'url' },
      { name: 'booking_url', label: 'Booking URL', type: 'url' },
      { name: 'office_hours', label: 'Office Hours', type: 'text' },
      { name: 'support_dark_mode', label: 'Support Dark Mode', type: 'checkbox', defaultValue: true },
      { name: 'contact_cta_title', label: 'Contact CTA Title', type: 'text' },
      { name: 'contact_cta_text', label: 'Contact CTA Text', type: 'textarea', rows: 4 },
      { name: 'og_image', label: 'OG Image Upload', type: 'file', accept: 'image/*', previewKey: 'og_image_source' },
      { name: 'og_image_url', label: 'OG Image URL', type: 'url' },
    ],
  },
  {
    key: 'socialLinks',
    label: 'Social Links',
    singular: 'Social Link',
    endpoint: '/dashboard/social-links/',
    titleKey: 'label',
    descriptionKey: 'platform',
    fields: [
      { name: 'platform', label: 'Platform', type: 'text' },
      { name: 'label', label: 'Label', type: 'text' },
      { name: 'url', label: 'URL', type: 'url' },
      { name: 'icon_name', label: 'Icon Name', type: 'text' },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'resumes',
    label: 'Resume Files',
    singular: 'Resume',
    endpoint: '/dashboard/resumes/',
    titleKey: 'title',
    descriptionKey: 'description',
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3 },
      { name: 'file', label: 'Resume Upload', type: 'file', accept: '.pdf,.doc,.docx', previewKey: 'file_source' },
      { name: 'file_url', label: 'Resume URL', type: 'url' },
      { name: 'is_primary', label: 'Primary Resume', type: 'checkbox', defaultValue: true },
    ],
  },
  {
    key: 'skillCategories',
    label: 'Skill Categories',
    singular: 'Skill Category',
    endpoint: '/dashboard/skill-categories/',
    titleKey: 'name',
    descriptionKey: 'description',
    fields: [
      { name: 'name', label: 'Name', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3 },
      { name: 'accent_color', label: 'Accent Color', type: 'text', placeholder: '#C48A3A' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'skills',
    label: 'Skills',
    singular: 'Skill',
    endpoint: '/dashboard/skills/',
    titleKey: 'name',
    descriptionKey: 'short_label',
    fields: [
      { name: 'category', label: 'Category', type: 'select', getOptions: (collections) => optionFromCollection(collections, 'skillCategories', 'name') },
      { name: 'name', label: 'Name', type: 'text' },
      { name: 'proficiency', label: 'Proficiency', type: 'number', defaultValue: 80 },
      { name: 'short_label', label: 'Short Label', type: 'text' },
      { name: 'icon_name', label: 'Icon Name', type: 'text' },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'services',
    label: 'Services',
    singular: 'Service',
    endpoint: '/dashboard/services/',
    titleKey: 'title',
    descriptionKey: 'short_description',
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'short_description', label: 'Short Description', type: 'textarea', rows: 3 },
      { name: 'details', label: 'Details', type: 'textarea', rows: 4 },
      { name: 'icon_name', label: 'Icon Name', type: 'text' },
      { name: 'highlight', label: 'Highlight', type: 'text' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'projects',
    label: 'Projects',
    singular: 'Project',
    endpoint: '/dashboard/projects/',
    titleKey: 'title',
    descriptionKey: 'summary',
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'summary', label: 'Summary', type: 'textarea', rows: 3 },
      { name: 'description', label: 'Description', type: 'textarea', rows: 5 },
      { name: 'category', label: 'Category', type: 'select', options: projectCategoryOptions },
      { name: 'status', label: 'Status', type: 'select', options: projectStatusOptions },
      { name: 'tech_stack', label: 'Tech Stack', type: 'list' },
      { name: 'features', label: 'Features', type: 'list' },
      { name: 'tags', label: 'Tags', type: 'list' },
      { name: 'thumbnail', label: 'Thumbnail Upload', type: 'file', accept: 'image/*', previewKey: 'thumbnail_source' },
      { name: 'thumbnail_url', label: 'Thumbnail URL', type: 'url' },
      { name: 'live_url', label: 'Live URL', type: 'url' },
      { name: 'github_url', label: 'GitHub URL', type: 'url' },
      { name: 'case_study_url', label: 'Case Study URL', type: 'url' },
      { name: 'client_name', label: 'Client Name', type: 'text' },
      { name: 'duration_text', label: 'Duration', type: 'text' },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'projectImages',
    label: 'Project Images',
    singular: 'Project Image',
    endpoint: '/dashboard/project-images/',
    titleKey: 'title',
    descriptionKey: 'caption',
    fields: [
      { name: 'project', label: 'Project', type: 'select', getOptions: (collections) => optionFromCollection(collections, 'projects', 'title') },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'image', label: 'Image Upload', type: 'file', accept: 'image/*', previewKey: 'image_source' },
      { name: 'image_url', label: 'Image URL', type: 'url' },
      { name: 'caption', label: 'Caption', type: 'textarea', rows: 3 },
      { name: 'is_primary', label: 'Primary', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'education',
    label: 'Education',
    singular: 'Education Item',
    endpoint: '/dashboard/education/',
    titleKey: 'degree_title',
    descriptionKey: 'institute_name',
    fields: [
      { name: 'degree_title', label: 'Degree Title', type: 'text' },
      { name: 'institute_name', label: 'Institute Name', type: 'text' },
      { name: 'start_year', label: 'Start Year', type: 'number' },
      { name: 'end_year', label: 'End Year', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 4 },
      { name: 'grade', label: 'Grade / CGPA', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'credential_url', label: 'Credential URL', type: 'url' },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'experience',
    label: 'Experience',
    singular: 'Experience Item',
    endpoint: '/dashboard/experience/',
    titleKey: 'role',
    descriptionKey: 'organization',
    fields: [
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'organization', label: 'Organization', type: 'text' },
      { name: 'start_date', label: 'Start Date', type: 'date' },
      { name: 'end_date', label: 'End Date', type: 'date' },
      { name: 'is_current', label: 'Current Role', type: 'checkbox' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'employment_type', label: 'Employment Type', type: 'text' },
      { name: 'summary', label: 'Summary', type: 'textarea', rows: 4 },
      { name: 'responsibilities', label: 'Responsibilities', type: 'list' },
      { name: 'achievements', label: 'Achievements', type: 'list' },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'certificates',
    label: 'Achievements / Certificates',
    singular: 'Achievement Card',
    endpoint: '/dashboard/certificates/',
    titleKey: 'title',
    descriptionKey: 'issuer',
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'issuer', label: 'Issuer', type: 'text' },
      { name: 'issue_date', label: 'Issue Date', type: 'date' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 4 },
      { name: 'credential_id', label: 'Credential ID', type: 'text' },
      { name: 'credential_url', label: 'Credential URL', type: 'url' },
      { name: 'image', label: 'Image Upload', type: 'file', accept: 'image/*', previewKey: 'image_source' },
      { name: 'image_url', label: 'Image URL', type: 'url' },
      { name: 'pdf_file', label: 'PDF Upload', type: 'file', accept: '.pdf', previewKey: 'pdf_source' },
      { name: 'pdf_url', label: 'PDF URL', type: 'url' },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'testimonials',
    label: 'Testimonials',
    singular: 'Testimonial',
    endpoint: '/dashboard/testimonials/',
    titleKey: 'name',
    descriptionKey: 'role',
    fields: [
      { name: 'name', label: 'Name', type: 'text' },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'organization', label: 'Organization', type: 'text' },
      { name: 'feedback', label: 'Feedback', type: 'textarea', rows: 4 },
      { name: 'photo', label: 'Photo Upload', type: 'file', accept: 'image/*', previewKey: 'photo_source' },
      { name: 'photo_url', label: 'Photo URL', type: 'url' },
      { name: 'rating', label: 'Rating', type: 'number', defaultValue: 5 },
      { name: 'is_featured', label: 'Featured', type: 'checkbox', defaultValue: true },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'galleryImages',
    label: 'Gallery',
    singular: 'Gallery Image',
    endpoint: '/dashboard/gallery-images/',
    titleKey: 'title',
    descriptionKey: 'caption',
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'image', label: 'Image Upload', type: 'file', accept: 'image/*', previewKey: 'image_source' },
      { name: 'image_url', label: 'Image URL', type: 'url' },
      { name: 'alt_text', label: 'Alt Text', type: 'text' },
      { name: 'caption', label: 'Caption', type: 'textarea', rows: 3 },
      { name: 'is_featured', label: 'Featured', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox', defaultValue: true },
      { name: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },
  {
    key: 'contactMessages',
    label: 'Inbox',
    singular: 'Message',
    endpoint: '/dashboard/contact-messages/',
    titleKey: 'subject',
    descriptionKey: 'name',
    allowCreate: false,
    fields: [
      { name: 'name', label: 'Name', type: 'text', readOnly: true },
      { name: 'email', label: 'Email', type: 'email', readOnly: true },
      { name: 'phone', label: 'Phone', type: 'text', readOnly: true },
      { name: 'subject', label: 'Subject', type: 'text', readOnly: true },
      { name: 'service_interest', label: 'Service Interest', type: 'text', readOnly: true },
      { name: 'budget_range', label: 'Budget Range', type: 'text', readOnly: true },
      { name: 'message', label: 'Message', type: 'textarea', rows: 6, readOnly: true },
      { name: 'source_page', label: 'Source Page', type: 'text', readOnly: true },
      { name: 'is_read', label: 'Marked Read', type: 'checkbox' },
      { name: 'is_replied', label: 'Marked Replied', type: 'checkbox' },
    ],
  },
]
